name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build project with Maven
        run: mvn clean install
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            tmux attach-session -t us_complex_server
            cd us_complex/us_complex_server/us_complex_server
            git pull origin main
            mvn spring-boot:run
      - name: Cancel workflow if deploy fails
        if: failure()
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.MGITHUB_TOKEN }}
          script: |
            const response = await github.actions.cancelWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });
            console.log(response);